baseURL = "https://terraformdns.github.io/"
languageCode = "en-us"
title = "Terraform DNS"
theme = "ananke"

[params]
  background_color_class = "bg-purple"
  featured_image = false
  description = "Terraform modules for creating DNS records"
  github = "https://github.com/terraformdns"
